#sudo: required

os: linux

language: generic

dist: Bionic

services:
  - docker

before_install:
  - docker build -t deutschkihun/complex-react-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true deutschkihun/complex-react-app npm run test -- --coverage

after_success:
  - docker build -t deutschkihun/docker-frontend ./frontend
  - docker build -t deutschkihun/docker-backend ./backend
  - docker build -t deutschkkhun/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push deutschkihun/docker-frontend
  - docker push deutschkihun/docker-backend
  - docker push deutschkihun/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "complex-docker-react-app"
  env: "ComplexDockerReactApp-env"
  bucket_name: "elasticbeanstalk-eu-central-1-183248202880"
  bucket_path: "complex-docker-react-app"
  on:
    branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_ACCESS_KEY
